### ISSUE TITLE
Add appropriate license

### ISSUE THREAD

**Issue by yue-dongchen** [brunocabral88/rent-it#82]
@brunocabral88 I'd like to fork and repurpose this project. Could you please add a license (e.g. GPLv3)?

Thanks.

**Comment by brunocabral88** [comment]
Hello @yue-dongchen, I have just added the license file.
Please note this repo has not been maintained for over 4 years, so pay close attention to the Dependabot alerts as it found many dependencies vulnerabilities (if you are thinking of ever putting it in production).
